# Generated by Django 5.2.5 on 2025-08-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_asset_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
    ]
