# Generated by Django 5.2.5 on 2025-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_asset_created_at_asset_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
